spring:
  application:
    name: stock-microservice
  graphql:
    path: /graphql
    graphiql:
      enabled: true
  cassandra:
    keyspace-name: portfolio_tracker
    username: <client_id>
    password: <client_secret>
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: src/main/resources/secure-connect-banking-stocks.zip

astra.db:
  id: <database_id>
  region: westus3
  keyspace: portfolio_tracker
  application.token: <token>
exchange-service:
  url: https://api.frankfurter.app/latest?from={from}&to={to}


#  cassandra:
 ## contact-points: 127.0.0.1
 ##keyspace-name: portfolio_tracker
 ## port: 9042
 ## local-datacenter: datacenter1
 ## schema-action: create_if_not_exists
